login:
    path: /login
    defaults: { _controller: BackendBundle:User:login}

login_check:
    path: /login_check

logout:
    path: /logout

backend_admin_dashboard:
    path: /dashboard
    defaults: { _controller: BackendBundle:Default:index}

backend_admin_list_user:
    path: /user/list
    defaults: {_controller: BackendBundle:User:list}

backend_admin_create_user:
    path: /user/create
    defaults: { _controller: BackendBundle:User:create }

backend_admin_list_ccpucp:
    path: /ccpucp/list
    defaults: {_controller: BackendBundle:Ccpucp:list}

backend_admin_delete_ccpucp:
    path: /ccpucp/delete/{id}
    defaults: {_controller: BackendBundle:Ccpucp:delete}


backend_admin_list_pucp:
    path: /pucp/list
    defaults: {_controller: BackendBundle:Pucp:list}

backend_admin_delete_pucp:
    path: /pucp/delete/{id}
    defaults: {_controller: BackendBundle:Pucp:delete}

backend_homepage:
    path: /
    defaults: { _controller: BackendBundle:User:login}

#backend_homepage:
#    path:     /
#    defaults: { _controller: BackendBundle:Default:index }
  